export default {
  appId: "@faako/dev-erp",
  brand: {
    name: "Dev ERP",
    businessName: "Faako",
    shortName: "DEV",
    browserChromeColor: "#f6f1e8",
  },
  theme: {
    presetId: "dev-erp",
    tokenOverrides: {
      "--sys-bg": "var(--surface)",
      "--sys-bg-elevated": "var(--neutral-soft)",
      "--sys-surface": "var(--card)",
      "--sys-surface-strong": "var(--surface)",
      "--sys-border": "var(--border)",
      "--sys-border-strong": "var(--border)",
      "--sys-text": "var(--ink)",
      "--sys-muted": "var(--muted)",
      "--sys-accent": "var(--accent)",
      "--sys-accent-contrast": "var(--surface)",
      "--sys-accent-soft": "var(--accent-soft)",
      "--sys-success": "var(--success)",
      "--sys-success-soft": "var(--success-soft)",
      "--sys-warning": "var(--warning)",
      "--sys-warning-soft": "var(--warning-soft)",
      "--sys-danger": "var(--danger)",
      "--sys-danger-soft": "var(--danger-soft)",
      "--sys-danger-contrast": "var(--surface)",
      "--sys-info": "var(--info)",
      "--sys-info-soft": "var(--info-soft)",
      "--sys-shadow-sm": "var(--shadow)",
      "--sys-shadow-md": "var(--shadow)",
      "--sys-shadow-lg": "var(--shadow)",
      "--sys-overlay": "var(--overlay)",
      "--erp-bg": "var(--surface)",
      "--erp-panel": "var(--card)",
      "--erp-panel-strong": "var(--card)",
      "--erp-border": "var(--border)",
      "--erp-ink": "var(--ink)",
      "--erp-muted": "var(--muted)",
      "--erp-accent": "var(--accent)",
      "--erp-sidebar-accent": "var(--accent)",
      "--erp-sidebar-bg": "var(--card)",
      "--erp-sidebar-panel": "color-mix(in oklab, var(--card), var(--surface) 18%)",
      "--erp-sidebar-border": "var(--border)",
      "--erp-sidebar-ink": "var(--ink)",
      "--erp-sidebar-muted": "var(--muted)",
      "--erp-sidebar-search-bg": "transparent",
      "--erp-sidebar-icon-bg": "color-mix(in oklab, var(--card), var(--surface) 18%)",
      "--erp-sidebar-active-bg": "var(--accent-soft)",
      "--erp-sidebar-shadow": "var(--shadow)",
      "--erp-brand-mark-bg": "transparent",
      "--erp-brand-mark-ring": "var(--border)",
      "--erp-search-placeholder": "color-mix(in oklab, var(--muted), var(--surface) 16%)",
      "--erp-search-hint-bg": "color-mix(in oklab, var(--card), var(--surface) 18%)",
      "--erp-scrollbar-thumb": "color-mix(in oklab, var(--muted), transparent 46%)",
      "--erp-link-hover-bg": "color-mix(in oklab, var(--accent-soft), var(--card) 32%)",
      "--erp-link-hover-border": "color-mix(in oklab, var(--accent), var(--border) 58%)",
      "--erp-link-focus-outline": "color-mix(in oklab, var(--accent), var(--border) 42%)",
      "--erp-link-active-border": "var(--accent)",
      "--erp-icon-ring": "var(--border)",
      "--erp-description": "var(--muted)",
      "--erp-empty-bg": "color-mix(in oklab, var(--card), var(--surface) 24%)",
      "--erp-frame-background": "var(--surface)",
      "--erp-bottom-nav-bg": "var(--card)",
      "--erp-bottom-nav-shadow": "var(--shadow)",
      "--erp-bottom-nav-active-bg": "var(--accent-soft)",
      "--erp-bottom-nav-icon-bg": "color-mix(in oklab, var(--accent-soft), var(--card) 20%)",
    },
  },
  security: {
    profileId: "authenticated-workspace",
    authMode: "cookie",
    allowedOrigins: [
      "http://localhost:5173",
      "http://127.0.0.1:5173",
      "http://localhost:4173",
      "http://localhost:8888",
      "https://dev.nanaabaackah.com",
      "https://faako.nanaabaackah.com",
    ],
  },
};
