export default {
  appId: "@faako/reebs-portal",
  brand: {
    name: "REEBS Portal",
    businessName: "REEBS Party Themes",
    shortName: "REEBS",
    browserChromeColor: "#ffffff",
  },
  theme: {
    presetId: "reebs-portal",
    tokenOverrides: {
      "--sys-bg": "var(--bg-base)",
      "--sys-bg-elevated": "var(--surface)",
      "--sys-surface": "var(--surface)",
      "--sys-surface-strong": "var(--card)",
      "--sys-border": "var(--border)",
      "--sys-border-strong": "rgba(var(--back3-rgb), 0.22)",
      "--sys-text": "var(--text-main)",
      "--sys-muted": "var(--muted)",
      "--sys-accent": "var(--accent)",
      "--sys-accent-contrast": "var(--dark)",
      "--sys-accent-soft": "var(--accent-soft)",
      "--sys-success": "var(--back2)",
      "--sys-success-soft": "rgba(var(--back2-rgb), 0.14)",
      "--sys-warning": "var(--other)",
      "--sys-warning-soft": "rgba(var(--other-rgb), 0.14)",
      "--sys-danger": "#b91c1c",
      "--sys-danger-soft": "rgba(185, 28, 28, 0.12)",
      "--sys-danger-contrast": "var(--white)",
      "--sys-info": "#2563eb",
      "--sys-info-soft": "rgba(37, 99, 235, 0.12)",
      "--sys-shadow-sm": "var(--shadow-sm)",
      "--sys-shadow-md": "var(--shadow-lg)",
      "--sys-shadow-lg": "var(--shadow-xl)",
      "--sys-overlay": "rgba(var(--ink-rgb), 0.36)",
      "--erp-bg": "var(--bg-base)",
      "--erp-panel": "var(--surface)",
      "--erp-panel-strong": "var(--card)",
      "--erp-border": "var(--border)",
      "--erp-ink": "var(--text-main)",
      "--erp-muted": "var(--muted)",
      "--erp-accent": "var(--accent)",
      "--erp-sidebar-accent": "var(--accent)",
      "--erp-sidebar-bg": "linear-gradient(180deg, var(--back3) 0%, var(--black) 100%)",
      "--erp-sidebar-panel":
        "linear-gradient(180deg, rgba(var(--black-rgb), 0.96), rgba(var(--back3-rgb), 0.98))",
      "--erp-sidebar-border": "rgba(var(--white-rgb), 0.12)",
      "--erp-sidebar-ink": "var(--white)",
      "--erp-sidebar-muted": "rgba(var(--white-rgb), 0.7)",
      "--erp-sidebar-search-bg": "rgba(var(--white-rgb), 0.06)",
      "--erp-sidebar-icon-bg": "rgba(var(--white-rgb), 0.08)",
      "--erp-sidebar-active-bg": "rgba(var(--other-rgb), 0.14)",
      "--erp-sidebar-shadow": "var(--shadow-xl)",
      "--erp-brand-mark-bg": "rgba(var(--other-rgb), 0.16)",
      "--erp-brand-mark-ring": "rgba(var(--other-rgb), 0.28)",
      "--erp-search-placeholder": "rgba(var(--white-rgb), 0.6)",
      "--erp-search-hint-bg": "rgba(var(--white-rgb), 0.08)",
      "--erp-scrollbar-thumb": "rgba(var(--white-rgb), 0.18)",
      "--erp-link-hover-bg": "rgba(var(--white-rgb), 0.06)",
      "--erp-link-hover-border": "rgba(var(--white-rgb), 0.1)",
      "--erp-link-focus-outline": "var(--other)",
      "--erp-link-active-border": "rgba(var(--other-rgb), 0.24)",
      "--erp-icon-ring": "rgba(var(--white-rgb), 0.08)",
      "--erp-description": "rgba(var(--white-rgb), 0.72)",
      "--erp-empty-bg": "rgba(var(--white-rgb), 0.04)",
      "--erp-frame-background": "var(--bg-base)",
      "--erp-bottom-nav-bg": "var(--card)",
      "--erp-bottom-nav-shadow": "var(--shadow-lg)",
      "--erp-bottom-nav-active-bg": "rgba(var(--other-rgb), 0.12)",
      "--erp-bottom-nav-icon-bg": "rgba(var(--other-rgb), 0.12)",
    },
  },
  security: {
    profileId: "authenticated-workspace",
    authMode: "cookie",
    allowedOrigins: [
      "https://www.reebspartythemes.com",
      "https://reebspartythemes.com",
      "https://portal.reebspartythemes.com",
      "http://localhost:5173",
      "http://localhost:5174",
      "http://localhost:8888",
    ],
  },
};
