[build]
command = "pnpm --filter @faako/reebs-erp build"
publish = "/apps/reebs-erp/dist"

[functions]
directory = "/apps/reebs-erp/netlify/functions"
node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
