export default {
  appId: "@faako/bynana-portfolio",
  brand: {
    name: "By Nana Portfolio",
    shortName: "BN",
    browserChromeColor: "#ebe5d4",
  },
  theme: {
    presetId: "bynana-portfolio",
    tokenOverrides: {
      "--sys-bg": "var(--surface-3)",
      "--sys-bg-elevated": "var(--surface-2)",
      "--sys-surface": "var(--glass-1)",
      "--sys-surface-strong": "var(--surface-1)",
      "--sys-border": "var(--line)",
      "--sys-border-strong": "var(--accent-line)",
      "--sys-text": "var(--text-1)",
      "--sys-muted": "var(--text-2)",
      "--sys-accent": "var(--accent)",
      "--sys-accent-contrast": "var(--surface-1)",
      "--sys-accent-soft": "var(--accent-soft)",
      "--sys-success": "#52664f",
      "--sys-success-soft": "rgba(82, 102, 79, 0.14)",
      "--sys-warning": "#8a6a2c",
      "--sys-warning-soft": "rgba(138, 106, 44, 0.14)",
      "--sys-danger": "#8a443c",
      "--sys-danger-soft": "rgba(138, 68, 60, 0.14)",
      "--sys-danger-contrast": "var(--surface-1)",
      "--sys-info": "#6b7b84",
      "--sys-info-soft": "rgba(107, 123, 132, 0.14)",
      "--sys-shadow-sm": "var(--shadow-soft)",
      "--sys-shadow-md": "var(--shadow-soft)",
      "--sys-shadow-lg": "var(--shadow-soft)",
      "--sys-overlay": "rgba(60, 60, 60, 0.32)",
    },
  },
  security: {
    profileId: "public-static",
    authMode: "none",
  },
};
