export default {
  appId: "@faako/faako-website",
  brand: {
    name: "Faako Website",
    businessName: "Faako",
    shortName: "FAAKO",
    browserChromeColor: "#fbfbfb",
  },
  theme: {
    presetId: "faako-website",
    tokenOverrides: {
      "--sys-bg": "var(--bg)",
      "--sys-bg-elevated": "var(--surface-alt)",
      "--sys-surface": "var(--surface)",
      "--sys-surface-strong": "var(--card)",
      "--sys-border": "var(--border)",
      "--sys-border-strong": "var(--header-border)",
      "--sys-text": "var(--ink)",
      "--sys-muted": "var(--muted)",
      "--sys-accent": "var(--accent)",
      "--sys-accent-contrast": "var(--surface)",
      "--sys-accent-soft": "color-mix(in srgb, var(--accent-soft) 36%, var(--surface))",
      "--sys-success": "var(--accent-strong)",
      "--sys-success-soft": "color-mix(in srgb, var(--accent-soft) 22%, var(--surface))",
      "--sys-warning": "#b86c2f",
      "--sys-warning-soft": "color-mix(in srgb, #b86c2f 14%, var(--surface))",
      "--sys-danger": "var(--danger)",
      "--sys-danger-soft": "color-mix(in srgb, var(--danger) 14%, var(--surface))",
      "--sys-danger-contrast": "var(--surface)",
      "--sys-info": "var(--accent)",
      "--sys-info-soft": "color-mix(in srgb, var(--accent) 14%, var(--surface))",
      "--sys-shadow-sm": "var(--shadow)",
      "--sys-shadow-md": "var(--shadow)",
      "--sys-shadow-lg": "var(--loose-shadow)",
      "--sys-overlay": "rgba(35, 88, 66, 0.24)",
    },
  },
  security: {
    profileId: "public-interactive",
    authMode: "none",
  },
};
