export default {
  appId: "@faako/faako-website",
  brand: {
    name: "Faako Website",
    businessName: "Faako",
    shortName: "FAAKO",
    browserChromeColor: "#fbfbfb",
  },
  theme: {
    presetId: "faako-website",
    tokenOverrides: {
      "--sys-bg": "var(--bg)",
      "--sys-bg-elevated": "var(--surface-alt)",
      "--sys-surface": "var(--surface)",
      "--sys-surface-strong": "var(--card)",
      "--sys-border": "var(--border)",
      "--sys-border-strong": "var(--accent-strong)",
      "--sys-text": "var(--ink)",
      "--sys-muted": "var(--muted)",
      "--sys-accent": "var(--accent)",
      "--sys-accent-contrast": "var(--surface)",
      "--sys-accent-soft": "var(--accent-soft)",
      "--sys-success": "var(--accent-strong)",
      "--sys-success-soft": "var(--section-bg)",
      "--sys-warning": "#a16207",
      "--sys-warning-soft": "rgba(161, 98, 7, 0.12)",
      "--sys-danger": "var(--danger)",
      "--sys-danger-soft": "color-mix(in srgb, var(--danger) 12%, transparent)",
      "--sys-danger-contrast": "var(--surface)",
      "--sys-info": "var(--accent)",
      "--sys-info-soft": "var(--section-bg)",
      "--sys-shadow-sm": "var(--glass-shadow)",
      "--sys-shadow-md": "var(--shadow)",
      "--sys-shadow-lg": "var(--loose-shadow)",
      "--sys-overlay": "rgba(21, 20, 25, 0.42)",
    },
  },
  security: {
    profileId: "public-interactive",
    authMode: "none",
  },
};
