[build]
  command = "npm --workspace apps/website run build"
  publish = "apps/website/dist"
  functions = "apps/website/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
