[build]
  command = "pnpm --filter @faako/faako-website build"
  publish = "/apps/faako-website/dist"

[functions]
  directory = "/apps/faako-website/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
