export type ReebsApiAudience = "public" | "customer" | "admin" | "system" | "webhook";
export type ReebsBusinessScope = "reebs-core" | "water" | "consolidated" | "shared";
export type ReebsBusinessUnit = "REEBS_CORE" | "WATER" | "CONSOLIDATED" | "SHARED";
export const REEBS_API_AUDIENCES: Readonly<Record<string, ReebsApiAudience>>;
export const REEBS_BUSINESS_SCOPES: Readonly<Record<string, ReebsBusinessScope>>;
export const REEBS_BUSINESS_UNITS: Readonly<Record<string, ReebsBusinessUnit>>;
export const REEBS_ERROR_CODES: Readonly<Record<string, string>>;
export const REEBS_API_V1_ROUTES: Readonly<Record<string, string>>;
export const REEBS_SAFE_ROUTE_INVENTORY: ReadonlyArray<Readonly<{ route: string; methods: readonly string[]; audience: string; scope: ReebsBusinessScope }>>;
export function toReebsSessionUserDto(user: Record<string, unknown>): Record<string, unknown>;
export function toReebsPublicProductDto(product: Record<string, unknown>): Record<string, unknown>;
export function toReebsCustomerSelfDto(customer: Record<string, unknown>): Record<string, unknown>;
export function toReebsAdminCustomerDto(customer: Record<string, unknown>): Record<string, unknown>;
export function toReebsPaymentInitializationDto(payment: Record<string, unknown>): Record<string, unknown>;
export function withReebsAnalyticsScope<T extends Record<string, unknown>>(data?: T): T & { scope: "reebs-core"; businessUnit: "REEBS_CORE" };
export function withWaterBusinessContext<T extends Record<string, unknown>>(data?: T): T & { scope: "water"; businessUnit: "WATER" };
export function withSharedBusinessContext<T extends Record<string, unknown>>(data?: T): T & { scope: "shared"; businessUnit: "SHARED" };
export function createConsolidatedAnalyticsResponse(input?: { reebsCore?: Record<string, unknown>; water?: Record<string, unknown> }): { scope: "consolidated"; businessUnit: "CONSOLIDATED"; components: Record<string, Record<string, unknown>> };
export function createReebsPaginationMeta(input?: { page?: number | string; pageSize?: number | string; total?: number | string }): { page: number; pageSize: number; total: number; totalPages: number };
