export const NOTIFICATION_CHANNELS = Object.freeze({
  EMAIL: "EMAIL",
  WHATSAPP: "WHATSAPP",
  SMS: "SMS",
  IN_APP: "IN_APP",
  COPY: "COPY",
});

export const NOTIFICATION_CHANNEL_LABELS = Object.freeze({
  [NOTIFICATION_CHANNELS.EMAIL]: "Email",
  [NOTIFICATION_CHANNELS.WHATSAPP]: "WhatsApp",
  [NOTIFICATION_CHANNELS.SMS]: "SMS",
  [NOTIFICATION_CHANNELS.IN_APP]: "In-app",
  [NOTIFICATION_CHANNELS.COPY]: "Copy",
});
