export const NOTIFICATION_STATUSES = Object.freeze({
  DRAFT: "DRAFT",
  READY: "READY",
  SENT: "SENT",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  USER_TRIGGERED: "USER_TRIGGERED",
});

export const NOTIFICATION_STATUS_LABELS = Object.freeze({
  [NOTIFICATION_STATUSES.DRAFT]: "Draft",
  [NOTIFICATION_STATUSES.READY]: "Ready",
  [NOTIFICATION_STATUSES.SENT]: "Sent",
  [NOTIFICATION_STATUSES.FAILED]: "Failed",
  [NOTIFICATION_STATUSES.CANCELLED]: "Cancelled",
  [NOTIFICATION_STATUSES.USER_TRIGGERED]: "User triggered",
});
