export const NOTIFICATION_TYPES = Object.freeze({
  RECEIPT: "RECEIPT",
  PAYMENT_REMINDER: "PAYMENT_REMINDER",
  BOOKING_CONFIRMATION: "BOOKING_CONFIRMATION",
  DELIVERY_UPDATE: "DELIVERY_UPDATE",
  LOW_STOCK_ALERT: "LOW_STOCK_ALERT",
  SYNC_FAILURE: "SYNC_FAILURE",
  GENERAL: "GENERAL",
});

export const NOTIFICATION_TYPE_LABELS = Object.freeze({
  [NOTIFICATION_TYPES.RECEIPT]: "Receipt",
  [NOTIFICATION_TYPES.PAYMENT_REMINDER]: "Payment reminder",
  [NOTIFICATION_TYPES.BOOKING_CONFIRMATION]: "Booking confirmation",
  [NOTIFICATION_TYPES.DELIVERY_UPDATE]: "Delivery update",
  [NOTIFICATION_TYPES.LOW_STOCK_ALERT]: "Low stock alert",
  [NOTIFICATION_TYPES.SYNC_FAILURE]: "Sync failure",
  [NOTIFICATION_TYPES.GENERAL]: "General",
});
