export default {
  appId: "@faako/stroane-web",
  brand: {
    name: "Stroane",
    businessName: "Stroane Solutions",
    shortName: "STROANE",
    browserChromeColor: "#ffffff",
  },
  theme: {
    presetId: "stroane-web",
    tokenOverrides: {
      "--sys-bg": "var(--color-bg)",
      "--sys-bg-elevated": "var(--color-white)",
      "--sys-surface": "var(--color-surface)",
      "--sys-surface-strong": "var(--color-surface)",
      "--sys-border": "var(--color-border-soft)",
      "--sys-border-strong": "var(--glass-card-border)",
      "--sys-text": "var(--color-text-primary)",
      "--sys-muted": "var(--color-text-secondary)",
      "--sys-accent": "var(--color-primary)",
      "--sys-accent-contrast": "var(--color-text-inverse)",
      "--sys-accent-soft": "var(--color-primary-tint)",
      "--sys-success": "var(--color-success)",
      "--sys-success-soft": "color-mix(in srgb, var(--color-success) 14%, transparent)",
      "--sys-warning": "var(--color-warning)",
      "--sys-warning-soft": "color-mix(in srgb, var(--color-warning) 14%, transparent)",
      "--sys-danger": "var(--color-danger)",
      "--sys-danger-soft": "color-mix(in srgb, var(--color-danger) 12%, transparent)",
      "--sys-danger-contrast": "var(--color-text-inverse)",
      "--sys-info": "var(--color-primary)",
      "--sys-info-soft": "var(--color-primary-tint)",
      "--sys-shadow-sm": "var(--shadow-card)",
      "--sys-shadow-md": "var(--shadow-elevated)",
      "--sys-shadow-lg": "var(--shadow-elevated)",
      "--sys-overlay": "var(--overlay-dark-soft)",
      "--erp-bg": "var(--sys-bg)",
      "--erp-panel": "var(--sys-surface)",
      "--erp-panel-strong": "var(--sys-surface-strong)",
      "--erp-border": "var(--sys-border)",
      "--erp-ink": "var(--sys-text)",
      "--erp-muted": "var(--sys-muted)",
      "--erp-accent": "var(--color-primary)",
      "--erp-sidebar-accent": "var(--color-text-inverse)",
      "--erp-sidebar-bg": "transparent",
      "--erp-sidebar-panel":
        "linear-gradient(180deg, var(--color-primary) 0%, var(--color-primary-dark) 100%)",
      "--erp-sidebar-border": "var(--footer-border)",
      "--erp-sidebar-ink": "var(--color-text-inverse)",
      "--erp-sidebar-muted": "var(--footer-text)",
      "--erp-sidebar-search-bg": "var(--footer-overlay)",
      "--erp-sidebar-icon-bg": "var(--footer-overlay)",
      "--erp-sidebar-active-bg": "var(--footer-overlay-hover)",
      "--erp-sidebar-shadow": "var(--shadow-elevated)",
      "--erp-brand-mark-bg": "var(--color-white)",
      "--erp-brand-mark-ring": "var(--footer-border)",
      "--erp-search-placeholder": "var(--footer-text-sub)",
      "--erp-search-hint-bg": "var(--footer-overlay)",
      "--erp-scrollbar-thumb": "var(--footer-overlay-hover)",
      "--erp-link-hover-bg": "var(--footer-overlay)",
      "--erp-link-hover-border": "var(--footer-border)",
      "--erp-link-focus-outline": "var(--color-primary-light)",
      "--erp-link-active-border": "var(--color-primary-light)",
      "--erp-icon-ring": "var(--footer-border)",
      "--erp-description": "var(--footer-text)",
      "--erp-empty-bg": "var(--footer-overlay)",
      "--erp-frame-background": "var(--sys-bg)",
      "--erp-bottom-nav-bg": "var(--sys-surface-strong)",
      "--erp-bottom-nav-shadow": "var(--sys-shadow-md)",
      "--erp-bottom-nav-active-bg": "var(--sys-accent-soft)",
      "--erp-bottom-nav-icon-bg": "var(--sys-accent-soft)",
    },
  },
  security: {
    profileId: "public-interactive",
    authMode: "none",
    allowedOrigins: [
      "https://stroane.example.com",
      "http://localhost:5173",
      "http://localhost:5175",
      "http://localhost:3000",
    ],
  },
};
