export default {
  appId: "@faako/stroane-web",
  brand: {
    name: "Stroane",
    businessName: "Stroane Solutions",
    shortName: "STROANE",
    browserChromeColor: "#ffffff",
  },
  theme: {
    presetId: "stroane-web",
    tokenOverrides: {
      "--sys-bg": "var(--bg-base)",
      "--sys-bg-elevated": "var(--light)",
      "--sys-surface": "var(--surface)",
      "--sys-surface-strong": "var(--card)",
      "--sys-border": "var(--border)",
      "--sys-border-strong": "rgba(var(--back3-rgb), 0.22)",
      "--sys-text": "var(--text-main)",
      "--sys-muted": "var(--muted)",
      "--sys-accent": "var(--accent)",
      "--sys-accent-contrast": "var(--dark)",
      "--sys-accent-soft": "var(--accent-soft)",
      "--sys-success": "var(--back2)",
      "--sys-success-soft": "rgba(var(--back2-rgb), 0.14)",
      "--sys-warning": "var(--other)",
      "--sys-warning-soft": "rgba(var(--other-rgb), 0.14)",
      "--sys-danger": "#b91c1c",
      "--sys-danger-soft": "rgba(185, 28, 28, 0.12)",
      "--sys-danger-contrast": "var(--white)",
      "--sys-info": "#2563eb",
      "--sys-info-soft": "rgba(37, 99, 235, 0.12)",
      "--sys-shadow-sm": "var(--shadow-sm)",
      "--sys-shadow-md": "var(--shadow-lg)",
      "--sys-shadow-lg": "var(--shadow-xl)",
      "--sys-overlay": "rgba(var(--ink-rgb), 0.36)",
    },
  },
  security: {
    profileId: "public-interactive",
    authMode: "none",
    allowedOrigins: [
      "https://stroane.example.com",
      "http://localhost:5173",
      "http://localhost:5175",
      "http://localhost:3000",
    ],
  },
};
