[build]
  command = "pnpm build"
  publish = "dist"

[dev]
  command = "pnpm dev:with-backend"
  port = 5175

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/api/:splat"
  status = 200
  force = true
  condition = "Role=admin"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
