export const OFFLINE_QUEUE_ACTION_TYPES = Object.freeze({
  CREATE_CUSTOMER: "CREATE_CUSTOMER",
  CREATE_POS_ORDER: "CREATE_POS_ORDER",
  CREATE_ORDER: "CREATE_ORDER",
  RECORD_PAYMENT: "RECORD_PAYMENT",
  CREATE_BOOKING: "CREATE_BOOKING",
  UPDATE_BOOKING_STATUS: "UPDATE_BOOKING_STATUS",
  UPDATE_BOOKING_DETAILS: "UPDATE_BOOKING_DETAILS",
  ADJUST_STOCK: "ADJUST_STOCK",
  UPDATE_DELIVERY_STATUS: "UPDATE_DELIVERY_STATUS",
  ADD_DELIVERY_NOTE: "ADD_DELIVERY_NOTE",
});

export const OFFLINE_QUEUE_ACTION_LABELS = Object.freeze({
  [OFFLINE_QUEUE_ACTION_TYPES.CREATE_CUSTOMER]: "Create customer",
  [OFFLINE_QUEUE_ACTION_TYPES.CREATE_POS_ORDER]: "Create POS order",
  [OFFLINE_QUEUE_ACTION_TYPES.CREATE_ORDER]: "Create order",
  [OFFLINE_QUEUE_ACTION_TYPES.RECORD_PAYMENT]: "Record payment",
  [OFFLINE_QUEUE_ACTION_TYPES.CREATE_BOOKING]: "Create booking",
  [OFFLINE_QUEUE_ACTION_TYPES.UPDATE_BOOKING_STATUS]: "Update booking status",
  [OFFLINE_QUEUE_ACTION_TYPES.UPDATE_BOOKING_DETAILS]: "Update booking details",
  [OFFLINE_QUEUE_ACTION_TYPES.ADJUST_STOCK]: "Adjust stock",
  [OFFLINE_QUEUE_ACTION_TYPES.UPDATE_DELIVERY_STATUS]: "Update delivery status",
  [OFFLINE_QUEUE_ACTION_TYPES.ADD_DELIVERY_NOTE]: "Add delivery note",
});
