export default {
  appId: "@faako/ttngh",
  brand: {
    name: "The Thriving Network GH",
    businessName: "The Thriving Network GH",
    shortName: "TTNGH",
    browserChromeColor: "#ffffff",
  },
  theme: {
    presetId: "ttngh",
    tokenOverrides: {
      "--sys-bg": "#fffdf9",
      "--sys-bg-elevated": "#f7f2ea",
      "--sys-surface": "#ffffff",
      "--sys-surface-strong": "#fffdf9",
      "--sys-border": "rgba(47, 52, 36, 0.12)",
      "--sys-border-strong": "rgba(47, 52, 36, 0.2)",
      "--sys-text": "#1f2a20",
      "--sys-muted": "#5c6d5d",
      "--sys-accent": "#7a9f62",
      "--sys-accent-contrast": "#ffffff",
      "--sys-accent-soft": "rgba(122, 159, 98, 0.12)",
      "--sys-success": "#2f7d4b",
      "--sys-success-soft": "rgba(47, 125, 75, 0.12)",
      "--sys-warning": "#c27d2a",
      "--sys-warning-soft": "rgba(194, 125, 42, 0.12)",
      "--sys-danger": "#b64d3c",
      "--sys-danger-soft": "rgba(182, 77, 60, 0.12)",
      "--sys-danger-contrast": "#ffffff",
      "--sys-info": "#305f9a",
      "--sys-info-soft": "rgba(48, 95, 154, 0.12)",
      "--sys-shadow-sm": "0 8px 18px rgba(31, 42, 32, 0.06)",
      "--sys-shadow-md": "0 16px 32px rgba(31, 42, 32, 0.1)",
      "--sys-shadow-lg": "0 26px 48px rgba(31, 42, 32, 0.14)",
      "--sys-overlay": "rgba(31, 42, 32, 0.42)",
    },
  },
  security: {
    profileId: "public-interactive",
    authMode: "cookie",
    allowedOrigins: [
      "https://www.thrivingnetworkgh.org",
      "https://thrivingnetworkgh.org",
      "http://localhost:5177",
    ],
  },
};
