export const AUDIT_ACTION_TYPES = Object.freeze({
  // Auth events
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  ROLE_UPDATED: "ROLE_UPDATED",
  USER_CREATED: "USER_CREATED",
  USER_DISABLED: "USER_DISABLED",
  ROLE_ASSIGNED: "ROLE_ASSIGNED",
  PERMISSION_CHANGED: "PERMISSION_CHANGED",

  // Payment events
  PAYMENT_RECORDED: "PAYMENT_RECORDED",
  PAYMENT_UPDATED: "PAYMENT_UPDATED",
  PAYMENT_CANCELLED: "PAYMENT_CANCELLED",
  PAYMENT_STATUS_CHANGED: "PAYMENT_STATUS_CHANGED",

  // Invoice events
  INVOICE_STATUS_CHANGED: "INVOICE_STATUS_CHANGED",

  // Order events
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_UPDATED: "ORDER_UPDATED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_COMPLETED: "ORDER_COMPLETED",

  // Booking events
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_UPDATED: "BOOKING_UPDATED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_COMPLETED: "BOOKING_COMPLETED",

  // Inventory events
  INVENTORY_ADJUSTED: "INVENTORY_ADJUSTED",
  STOCK_RESERVED: "STOCK_RESERVED",
  STOCK_RELEASED: "STOCK_RELEASED",

  // Offline sync events
  OFFLINE_SYNC_QUEUED: "OFFLINE_SYNC_QUEUED",
  OFFLINE_SYNC_RETRIED: "OFFLINE_SYNC_RETRIED",
  OFFLINE_SYNC_COMPLETED: "OFFLINE_SYNC_COMPLETED",
  OFFLINE_SYNC_FAILED: "OFFLINE_SYNC_FAILED",
  OFFLINE_SYNC_CONFLICT: "OFFLINE_SYNC_CONFLICT",
  OFFLINE_QUEUE_ITEM_CANCELLED: "OFFLINE_QUEUE_ITEM_CANCELLED",
  OFFLINE_QUEUE_ITEM_RESOLVED: "OFFLINE_QUEUE_ITEM_RESOLVED",

  // Settings events
  SETTINGS_UPDATED: "SETTINGS_UPDATED",
  ORGANIZATION_SETTINGS_CHANGED: "ORGANIZATION_SETTINGS_CHANGED",
  INTEGRATION_ENABLED: "INTEGRATION_ENABLED",
  INTEGRATION_DISABLED: "INTEGRATION_DISABLED",

  // System events
  SYSTEM_EVENT: "SYSTEM_EVENT",
  ADMIN_ACTION: "ADMIN_ACTION",
});

export const AUDIT_ACTION_LABELS = Object.freeze({
  [AUDIT_ACTION_TYPES.LOGIN_SUCCESS]: "Login successful",
  [AUDIT_ACTION_TYPES.LOGIN_FAILURE]: "Login failed",
  [AUDIT_ACTION_TYPES.LOGOUT]: "Logged out",
  [AUDIT_ACTION_TYPES.SESSION_EXPIRED]: "Session expired",
  [AUDIT_ACTION_TYPES.ROLE_UPDATED]: "Role updated",
  [AUDIT_ACTION_TYPES.USER_CREATED]: "User created",
  [AUDIT_ACTION_TYPES.USER_DISABLED]: "User disabled",
  [AUDIT_ACTION_TYPES.ROLE_ASSIGNED]: "Role assigned",
  [AUDIT_ACTION_TYPES.PERMISSION_CHANGED]: "Permission changed",

  [AUDIT_ACTION_TYPES.PAYMENT_RECORDED]: "Payment recorded",
  [AUDIT_ACTION_TYPES.PAYMENT_UPDATED]: "Payment updated",
  [AUDIT_ACTION_TYPES.PAYMENT_CANCELLED]: "Payment cancelled",
  [AUDIT_ACTION_TYPES.PAYMENT_STATUS_CHANGED]: "Payment status changed",
  [AUDIT_ACTION_TYPES.INVOICE_STATUS_CHANGED]: "Invoice status changed",

  [AUDIT_ACTION_TYPES.ORDER_CREATED]: "Order created",
  [AUDIT_ACTION_TYPES.ORDER_UPDATED]: "Order updated",
  [AUDIT_ACTION_TYPES.ORDER_CANCELLED]: "Order cancelled",
  [AUDIT_ACTION_TYPES.ORDER_COMPLETED]: "Order completed",

  [AUDIT_ACTION_TYPES.BOOKING_CREATED]: "Booking created",
  [AUDIT_ACTION_TYPES.BOOKING_UPDATED]: "Booking updated",
  [AUDIT_ACTION_TYPES.BOOKING_CANCELLED]: "Booking cancelled",
  [AUDIT_ACTION_TYPES.BOOKING_COMPLETED]: "Booking completed",

  [AUDIT_ACTION_TYPES.INVENTORY_ADJUSTED]: "Inventory adjusted",
  [AUDIT_ACTION_TYPES.STOCK_RESERVED]: "Stock reserved",
  [AUDIT_ACTION_TYPES.STOCK_RELEASED]: "Stock released",

  [AUDIT_ACTION_TYPES.OFFLINE_SYNC_QUEUED]: "Queued for offline sync",
  [AUDIT_ACTION_TYPES.OFFLINE_SYNC_RETRIED]: "Offline sync retried",
  [AUDIT_ACTION_TYPES.OFFLINE_SYNC_COMPLETED]: "Offline sync completed",
  [AUDIT_ACTION_TYPES.OFFLINE_SYNC_FAILED]: "Offline sync failed",
  [AUDIT_ACTION_TYPES.OFFLINE_SYNC_CONFLICT]: "Offline sync conflict detected",
  [AUDIT_ACTION_TYPES.OFFLINE_QUEUE_ITEM_CANCELLED]: "Queue item cancelled",
  [AUDIT_ACTION_TYPES.OFFLINE_QUEUE_ITEM_RESOLVED]: "Queue item marked resolved",

  [AUDIT_ACTION_TYPES.SETTINGS_UPDATED]: "Settings updated",
  [AUDIT_ACTION_TYPES.ORGANIZATION_SETTINGS_CHANGED]: "Organization settings changed",
  [AUDIT_ACTION_TYPES.INTEGRATION_ENABLED]: "Integration enabled",
  [AUDIT_ACTION_TYPES.INTEGRATION_DISABLED]: "Integration disabled",

  [AUDIT_ACTION_TYPES.SYSTEM_EVENT]: "System event",
  [AUDIT_ACTION_TYPES.ADMIN_ACTION]: "Admin action",
});
