export default {
  appId: "@faako/faako-erp",
  brand: {
    name: "Faako ERP",
    businessName: "Faako",
    shortName: "FAAKO",
    browserChromeColor: "#fbfbfb",
  },
  theme: {
    presetId: "faako-erp",
    tokenOverrides: {
      "--sys-bg": "var(--bg)",
      "--sys-bg-elevated": "var(--surface-alt)",
      "--sys-surface": "var(--surface)",
      "--sys-surface-strong": "var(--card)",
      "--sys-border": "var(--border)",
      "--sys-border-strong": "var(--header-border)",
      "--sys-text": "var(--ink)",
      "--sys-muted": "var(--muted)",
      "--sys-accent": "var(--accent)",
      "--sys-accent-contrast": "var(--surface)",
      "--sys-accent-soft": "color-mix(in srgb, var(--accent-soft) 36%, var(--surface))",
      "--sys-success": "var(--success)",
      "--sys-success-soft": "var(--success-soft)",
      "--sys-warning": "var(--warning)",
      "--sys-warning-soft": "var(--warning-soft)",
      "--sys-danger": "var(--danger)",
      "--sys-danger-soft": "color-mix(in srgb, var(--danger) 14%, var(--surface))",
      "--sys-danger-contrast": "var(--surface)",
      "--sys-info": "var(--accent)",
      "--sys-info-soft": "var(--info-soft)",
      "--sys-shadow-sm": "var(--shadow)",
      "--sys-shadow-md": "var(--shadow)",
      "--sys-shadow-lg": "var(--loose-shadow)",
      "--sys-overlay": "rgba(35, 88, 66, 0.24)",
      "--erp-bg": "var(--surface)",
      "--erp-panel": "var(--card)",
      "--erp-panel-strong": "var(--card)",
      "--erp-border": "var(--border)",
      "--erp-ink": "var(--ink)",
      "--erp-muted": "var(--muted)",
      "--erp-accent": "var(--accent)",
      "--erp-sidebar-accent": "color-mix(in oklab, var(--accent), var(--surface) 18%)",
      "--erp-sidebar-bg":
        "radial-gradient(circle at top left, color-mix(in oklab, var(--accent), transparent 82%), transparent 22%), linear-gradient(180deg, color-mix(in oklab, var(--ink), var(--accent) 18%) 0%, color-mix(in oklab, var(--ink), var(--accent) 12%) 52%, color-mix(in oklab, var(--ink), var(--surface) 12%) 100%)",
      "--erp-sidebar-panel":
        "linear-gradient(180deg, color-mix(in oklab, var(--ink), var(--accent) 20%), color-mix(in oklab, var(--ink), var(--surface) 10%))",
      "--erp-sidebar-border": "color-mix(in oklab, var(--surface), transparent 84%)",
      "--erp-sidebar-ink": "color-mix(in oklab, var(--surface), var(--card) 26%)",
      "--erp-sidebar-muted": "color-mix(in oklab, var(--surface), var(--muted) 28%)",
      "--erp-sidebar-search-bg": "color-mix(in oklab, var(--surface), transparent 95%)",
      "--erp-sidebar-icon-bg": "color-mix(in oklab, var(--surface), transparent 94%)",
      "--erp-sidebar-active-bg": "color-mix(in oklab, var(--accent), transparent 84%)",
      "--erp-sidebar-shadow": "0 28px 60px color-mix(in oklab, var(--ink), transparent 62%)",
      "--erp-brand-mark-bg": "color-mix(in oklab, var(--accent), transparent 78%)",
      "--erp-brand-mark-ring": "color-mix(in oklab, var(--accent), transparent 66%)",
      "--erp-search-placeholder": "color-mix(in oklab, var(--surface), var(--muted) 34%)",
      "--erp-search-hint-bg": "color-mix(in oklab, var(--surface), transparent 94%)",
      "--erp-scrollbar-thumb": "color-mix(in oklab, var(--surface), transparent 76%)",
      "--erp-link-hover-bg": "color-mix(in oklab, var(--surface), transparent 95%)",
      "--erp-link-hover-border": "color-mix(in oklab, var(--surface), transparent 90%)",
      "--erp-link-focus-outline": "var(--erp-sidebar-accent)",
      "--erp-link-active-border": "color-mix(in oklab, var(--accent), transparent 72%)",
      "--erp-icon-ring": "color-mix(in oklab, var(--surface), transparent 92%)",
      "--erp-description": "color-mix(in oklab, var(--surface), var(--muted) 22%)",
      "--erp-empty-bg": "color-mix(in oklab, var(--surface), transparent 96%)",
      "--erp-frame-background":
        "linear-gradient(180deg, color-mix(in oklab, var(--card), transparent 28%), transparent 28%), var(--surface)",
      "--erp-bottom-nav-bg": "color-mix(in oklab, var(--card), transparent 4%)",
      "--erp-bottom-nav-shadow": "0 18px 34px color-mix(in oklab, var(--ink), transparent 76%)",
      "--erp-bottom-nav-active-bg": "color-mix(in oklab, var(--accent), transparent 92%)",
      "--erp-bottom-nav-icon-bg": "color-mix(in oklab, var(--accent), transparent 90%)",
    },
  },
  security: {
    profileId: "authenticated-workspace",
    authMode: "cookie",
    allowedOrigins: [
      "http://localhost:5176",
      "http://127.0.0.1:5176",
      "https://faako.nanaabaackah.com",
    ],
  },
};
