[build]
  command = "pnpm --filter @faako/faako-erp build"
  ignore = "node ./scripts/netlify-ignore.mjs @faako/faako-erp"
  publish = "/apps/faako-erp/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
