import { defineErpShellConfig } from "@faako/config";

export default defineErpShellConfig({
  brand: {
    name: "REEBS ERP",
    shortName: "REEBS",
    sidebarTitle: "REEBS Portal",
    homePath: "/admin",
    topbarLabel: "Admin workspace",
    publicUrl: "https://reebspartythemes.com",
    shellVars: {
      "--erp-accent": "#ff9932",
      "--erp-bg": "#f6f7f9",
      "--erp-panel": "rgba(255, 255, 255, 0.88)",
      "--erp-panel-strong": "rgba(255, 255, 255, 0.95)",
      "--erp-border": "rgba(58, 63, 69, 0.18)",
      "--erp-ink": "#23262c",
      "--erp-muted": "#646b74",
    },
  },
  pageTitles: {
    "/login": "Login",
    "/reset-password": "Reset Password",
    "/admin": "Dashboard",
    "/admin/inventory": "Inventory",
    "/admin/store-mode": "Store Mode",
    "/admin/purchases": "Purchases",
    "/admin/offline": "Offline",
    "/admin/advanced": "Settings",
    "/admin/orders": "Orders",
    "/admin/orders/new": "New Order",
    "/admin/crm": "CRM",
    "/admin/customers": "Customers",
    "/admin/users": "Users",
    "/admin/employees": "Employees",
    "/admin/website-template": "Settings",
    "/admin/directory": "Directory",
    "/admin/accounting": "Accounting",
    "/admin/expenses": "Expenses",
    "/admin/water": "Water",
    "/admin/vendors": "Vendors",
    "/admin/delivery": "Delivery",
    "/admin/documents": "Documents",
    "/admin/timesheets": "Timesheets",
    "/admin/profile": "My Profile",
    "/admin/settings": "Settings",
    "/admin/hr": "HR",
    "/admin/roles": "Roles",
    "/admin/maintenance": "Maintenance",
    "/admin/invoicing": "Invoicing",
    "/admin/marketing": "Marketing",
    "/admin/schedule": "Schedule",
    "/admin/bookings": "Bookings",
  },
});
