export const projectDetails = [
  {
    slug: 'reconstruction',
    seo: {
      title: 'Projects | Intranet Website Redesign | By Nana',
      description:
        'Case study: intranet redesign + internal learning system built for simple, accessible workflows across a mixed-age workforce.',
      path: '/projects/reconstruction',
    },
    eyebrow: 'Case study',
    title: 'Intranet Website Redesign',
    summary:
      'A cluttered intranet and separate learning resources were unified into one simple, accessible internal platform designed for cross-department staff, including older team members.',
    heroImage: '/imgs/mockups/ibw/IBW_1.png',
    supportingImages: ['/imgs/mockups/ibw/IBW_3.png', '/imgs/mockups/ibw/IBW_2.png'],
    discoveryImage: '/imgs/mockups/ibw/IBW_4.png',
    pills: ['Intranet redesign', 'Learning system', 'Accessibility-first', 'Google Workspace', 'Enablement'],
    heroFacts: [
      { label: 'Deliverables', value: 'Intranet Website + Internal Learning Hub' },
      { label: 'Stack', value: 'Google Sites, HTML/CSS/JS, Figma, Google Drive' },
      { label: 'Role', value: 'Front-End Developer' },
      { label: 'Service', value: 'UX Audit + IA + Accessibility-led Redesign' },
    ],
    atAGlance: [
      { label: 'Product', value: 'Intranet website + integrated internal learning system' },
      { label: 'Users', value: 'Cross-department staff, including older and non-technical users' },
      { label: 'Goal', value: 'Simple navigation, clearer onboarding, and lower support dependency' },
      { label: 'Tools', value: 'Google Sites, HTML/CSS/JS, Figma, Google Drive' },
    ],
    stats: [
      { value: '30%', label: 'Support requests reduced' },
      { value: '2', label: 'Internal systems merged into one platform' },
      { value: 'Task-first', label: 'Navigation model across key workflows' },
      { value: 'Self-serve', label: 'Content updates enabled' },
    ],
    challenges: [
      'Intranet content was scattered across duplicate pages, outdated files, and inconsistent link structures, making routine task lookup slow and frustrating.',
      'A large part of the intranet audience was older staff, so dense layouts, small text, and deep navigation trees caused avoidable confusion and support dependency.',
      'The internal learning resources were disconnected from the intranet, which fragmented onboarding and made it harder for teams to follow one consistent training path.',
    ],
    storefrontShowcase: {
      label: '[Intranet + Learning Hub]',
      headline:
        'THE REDESIGNED INTRANET NOW GUIDES STAFF INTO TASKS AND TRAINING WITH MINIMAL COGNITIVE LOAD.',
      paragraphs: [
        'The experience was simplified into clear, high-contrast entry points so staff can move from homepage to key operational actions without getting lost in nested pages.',
        'Learning modules were brought into the same ecosystem, so onboarding and daily references now live in one predictable interface with consistent labels and structure.',
      ],
      image: '/imgs/mockups/ibw/IBW_7.png',
    },
    sections: [
      {
        id: 'problem',
        title: 'Problem and Constraints',
        image: '/imgs/mockups/ibw/IBW_4.png',
        list: [
          'Google Sites platform constraints limited how far layout and interaction patterns could go.',
          'Content sprawl from duplicate links and outdated documents.',
          'The user base included many older staff, so readability and ease of use were non-negotiable.',
          'Adoption risk required training and documentation alongside launch.',
        ],
      },
      {
        id: 'design-strategy',
        title: 'Design Strategy for Older and Non-Technical Users',
        image: '/imgs/mockups/ibw/IBW_5.png',
        list: [
          'Simplified information architecture to reduce decision fatigue and click depth.',
          'Larger typography, stronger visual hierarchy, and higher contrast for easier scanning.',
          'Plain-language labels and descriptive navigation names instead of internal jargon.',
          'Clear task grouping (forms, reports, policies, onboarding) with consistent page templates.',
          'Accessibility checks for keyboard navigation, readable spacing, and predictable interaction patterns.',
        ],
      },
      {
        id: 'learning-system',
        title: 'Integrated Internal Learning System',
        image: '/imgs/mockups/ibw/IBW_8.png',
        cards: [
          { title: 'Single learning entry point', detail: 'Training materials moved into one structured path from the intranet.' },
          { title: 'Role-based module grouping', detail: 'New hires, managers, and content owners follow clearer tracks.' },
          { title: 'Drive-native maintenance', detail: 'Content owners update training resources without engineering support.' },
          { title: 'Onboarding consistency', detail: 'Teams get one reliable source for SOPs, videos, and reference docs.' },
        ],
      },
      {
        id: 'before-after',
        title: 'Before and After',
        image: '/imgs/mockups/ibw/IBW_9.png',
        compare: {
          beforeLabel: 'Before',
          before: [
            'Fragmented intranet and learning resources',
            'Deep navigation and inconsistent naming',
            'Harder usability for older staff',
            'High support requests for routine tasks',
          ],
          afterLabel: 'After',
          after: [
            'One intranet hub for tasks and training',
            'Task-first routes with simplified labels',
            'Accessible, readable interface patterns',
            'Lower support load via self-serve usage',
          ],
        },
      },
      {
        id: 'rollout',
        title: 'Delivery and Rollout',
        image: '/imgs/mockups/ibw/IBW_10.png',
        cards: [
          { title: 'Plan', detail: 'Content inventory, IA cleanup, and stakeholder walkthroughs.' },
          { title: 'Build', detail: 'Responsive HTML/CSS/JS components embedded in Google Sites.' },
          { title: 'Enable', detail: 'Training, quick guides, and update ownership for continuity.' },
        ],
      },
    ],
    actions: [
      { label: 'Back to projects', href: '/projects' },
      { label: 'Book a working session', href: 'https://dev.nanaabaackah.com/book', external: true },
    ],
  },
  {
    slug: 'development-tracker',
    seo: {
      title: 'Projects | Development Operations System | By Nana',
      description:
        'Case study: Dev ERP internal operations portal with dashboard, rent, accounting, invoicing, appointments, reports, user access, alerts, and system monitoring.',
      path: '/projects/development-tracker',
    },
    eyebrow: 'Case study',
    title: 'Development Operations System (Dev ERP)',
    summary:
      'A standalone internal operations portal that combines dashboard metrics, rent management, accounting, invoicing, appointments, reporting, user access, alerts, and system-health monitoring in one Dev ERP workspace.',
    heroImage: '/imgs/mockups/dev/DEV_1.png',
    supportingImages: ['/imgs/mockups/dev/DEV_4.png', '/imgs/mockups/dev/DEV_2.png'],
    discoveryImage: '/imgs/mockups/dev/DEV_3.png',
    pills: ['Dev ERP', 'React + Express', 'Prisma + PostgreSQL', 'Cookie sessions + CSRF', 'Calendar + alerts'],
    heroFacts: [
      { label: 'Deliverables', value: 'Internal Operations Portal' },
      { label: 'Stack', value: 'React/Vite, Express, Prisma, PostgreSQL' },
      { label: 'Role', value: 'Full-Stack Product Engineer' },
      { label: 'Service', value: 'Architecture + ERP Product Delivery' },
    ],
    atAGlance: [
      { label: 'Product', value: 'Dev ERP operations portal + backend' },
      { label: 'Users', value: 'Admin, operations, finance, rent-only users, contributors' },
      {
        label: 'Scope',
        value:
          'Dashboard, rent, accounting, invoicing, appointments, organizations, user control, reports, audit logs, settings, system health, alerts',
      },
      { label: 'Tools', value: 'React/Vite, Express route slices, Prisma schema + migrations, PostgreSQL, Netlify frontend proxy' },
    ],
    stats: [
      { value: '12', label: 'Core app modules in main navigation' },
      { value: 'Vertical slices', label: 'Auth, users, dashboard, jobs, productivity, security, and org scope' },
      { value: 'Cookie + CSRF', label: 'Session security model' },
      { value: 'Org-scoped', label: 'Organization hierarchy and capability-based access model' },
    ],
    challenges: [
      'Operational data for rent, accounting, invoicing, appointments, reporting, and system status needed to live in one workspace without flattening user roles or organization boundaries.',
      'The backend had to move toward focused vertical route slices while preserving secure session handling, CSRF checks, capability enforcement, and database isolation safeguards.',
      'Public appointment booking, Google Calendar sync, report delivery, email/SMS alerts, and system-health checks needed to coexist with a maintainable Express and Prisma architecture.',
    ],
    storefrontShowcase: {
      label: '[Dev ERP Workspace]',
      headline:
        'DEV ERP NOW CONNECTS OPERATIONS, FINANCE, APPOINTMENTS, ACCESS CONTROL, AND SYSTEM HEALTH.',
      paragraphs: [
        'The interface gives admins and role-scoped users one control center for dashboard metrics, rent, accounting, invoicing, appointments, reports, audit logs, and system health.',
        'Behind the UI, modular Express route slices and a Prisma-backed Postgres schema keep each workflow connected through shared session, CSRF, capability, and organization-scope rules.',
      ],
      image: '/imgs/mockups/dev/DEV_11.png',
    },
    diagrams: [
      {
        id: 'dev-tracker-system-layout',
        type: 'architecture',
        title: 'Architecture Diagram',
        caption: 'Vite frontend modules, modular Express API slices, Prisma data model, and external operations integrations.',
        ariaLabel:
          'System architecture for Dev ERP showing Vite admin portal, public appointment booking, auth and capability middleware, modular Express API, Prisma Postgres, Google Calendar, and alerts.',
        nodes: [
          { id: 'ui', label: 'Vite Admin Portal', detail: '12 role-aware modules', x: 15, y: 18, tone: 'accent' },
          { id: 'public-book', label: 'Public Appointment', detail: 'Org-scoped booking page', x: 49, y: 10, tone: 'light' },
          { id: 'auth', label: 'Auth Sessions', detail: 'Secure cookie flow', x: 78, y: 18, tone: 'light' },
          { id: 'capabilities', label: 'Capability Rules', detail: 'Role and module checks', x: 83, y: 38, tone: 'light' },
          { id: 'api', label: 'Modular Express API', detail: 'Route slices and middleware', x: 50, y: 46, tone: 'accent' },
          { id: 'prisma', label: 'Prisma ORM', detail: 'Schema and migrations', x: 42, y: 74, tone: 'light' },
          { id: 'db', label: 'PostgreSQL Database', detail: 'Ops, finance, rent data', x: 58, y: 84, tone: 'light' },
          { id: 'google', label: 'Google Calendar', detail: 'Appointment sync', x: 17, y: 87, tone: 'base' },
          { id: 'email', label: 'Email Alerts', detail: 'Reports and notices', x: 77, y: 77, tone: 'base' },
          { id: 'sms', label: 'SMS Alerts', detail: 'Operational notices', x: 88, y: 87, tone: 'base' },
          { id: 'jobs', label: 'Scheduled Jobs', detail: 'Reports and system tasks', x: 75, y: 92, tone: 'base' },
        ],
        edges: [
          { from: 'ui', to: 'api', label: 'module APIs', labelT: 0.6, labelOffset: -1.6 },
          { from: 'public-book', to: 'api', label: 'appointment APIs', labelT: 0.4, labelOffset: -2.2 },
          { from: 'auth', to: 'api', label: 'capability checks', labelT: 0.62, labelOffset: 1.6 },
          { from: 'capabilities', to: 'api', label: 'allow or deny' },
          { from: 'api', to: 'prisma', label: 'data access' },
          { from: 'prisma', to: 'db', label: 'SQL queries' },
          { from: 'api', to: 'google', label: 'calendar sync' },
          { from: 'api', to: 'email', label: 'email notices' },
          { from: 'api', to: 'sms', label: 'text notices' },
          { from: 'api', to: 'jobs', label: 'scheduled jobs' },
        ],
      },
      {
        id: 'dev-tracker-db-layout',
        type: 'class',
        title: 'Database Class Diagram',
        caption: 'Key entities, attributes, and relationships from the Dev ERP Prisma schema.',
        ariaLabel:
          'Database class diagram for Dev ERP with organization hierarchy, roles, users, appointments, accounting, invoices, rent tenants, rent payments, productivity, and calendar settings.',
        nodes: [
          {
            id: 'org',
            label: 'Organization',
            tone: 'accent',
            x: 13,
            y: 18,
            attributes: ['id: uuid', 'name: string', 'slug: string', 'status: enum', 'settings: json'],
          },
          {
            id: 'role',
            label: 'Role',
            tone: 'light',
            x: 34,
            y: 18,
            attributes: ['id: uuid', 'organizationId: fk', 'name: string', 'permissions: json'],
          },
          {
            id: 'user',
            label: 'User',
            tone: 'light',
            x: 55,
            y: 18,
            attributes: ['id: uuid', 'organizationId: fk', 'roleId: fk', 'email: string', 'status: enum'],
          },
          {
            id: 'booking',
            label: 'Appointment',
            tone: 'accent',
            x: 79,
            y: 18,
            attributes: ['id: uuid', 'organizationId: fk', 'customerName: string', 'scheduledAt: datetime', 'calendarEventId: string'],
          },
          {
            id: 'invoice',
            label: 'Invoice',
            tone: 'base',
            x: 21,
            y: 49,
            attributes: ['id: uuid', 'organizationId: fk', 'clientName: string', 'status: enum', 'total: decimal'],
          },
          {
            id: 'invoiceLineItem',
            label: 'InvoiceLineItem',
            tone: 'base',
            x: 31,
            y: 49,
            attributes: ['id: uuid', 'invoiceId: fk', 'description: string', 'quantity: int', 'unitPrice: decimal'],
          },
          {
            id: 'accounting',
            label: 'AccountingEntry',
            tone: 'light',
            x: 43,
            y: 49,
            attributes: ['id: uuid', 'organizationId: fk', 'type: enum', 'amount: decimal', 'postedAt: datetime'],
          },
          {
            id: 'rentTenant',
            label: 'RentTenant',
            tone: 'light',
            x: 66,
            y: 49,
            attributes: ['id: uuid', 'organizationId: fk', 'tenantName: string', 'unit: string', 'status: enum'],
          },
          {
            id: 'rentPayment',
            label: 'RentPayment',
            tone: 'light',
            x: 76,
            y: 49,
            attributes: ['id: uuid', 'tenantId: fk', 'amount: decimal', 'paidAt: datetime', 'method: enum'],
          },
          {
            id: 'calendar',
            label: 'CalendarSettings',
            tone: 'base',
            x: 86,
            y: 49,
            attributes: ['id: uuid', 'organizationId: fk', 'provider: string', 'oauthState: json', 'bookingConfig: json'],
          },
          {
            id: 'productivity',
            label: 'ProductivityEntry',
            tone: 'base',
            x: 50,
            y: 81,
            attributes: ['id: uuid', 'organizationId: fk', 'userId: fk', 'status: enum', 'dueAt: datetime'],
          },
        ],
        edges: [
          { from: 'org', to: 'role', label: '1 -> many' },
          { from: 'org', to: 'user', label: '1 -> many' },
          { from: 'org', to: 'booking', label: '1 -> many' },
          { from: 'org', to: 'invoice', label: '1 -> many' },
          { from: 'org', to: 'rentTenant', label: '1 -> many' },
          { from: 'org', to: 'calendar', label: '1 -> 1' },
          { from: 'org', to: 'accounting', label: '1 -> many' },
          { from: 'org', to: 'productivity', label: '1 -> many' },
          { from: 'role', to: 'user', label: '1 -> many' },
          { from: 'invoice', to: 'invoiceLineItem', label: '1 -> many' },
          { from: 'rentTenant', to: 'rentPayment', label: '1 -> many' },
          { from: 'user', to: 'productivity', label: '1 -> many' },
          { from: 'booking', to: 'calendar', label: 'syncs with' },
        ],
      },
    ],
    sections: [
      {
        id: 'workspace-modules',
        title: 'Workspace Modules',
        image: '/imgs/mockups/dev/DEV_6.png',
        cards: [
          { title: 'Dashboard', detail: 'KPI, availability, site status, and operational health overview.' },
          { title: 'Rent', detail: 'Tenant records, rent payment history, balances, and rent-only user paths.' },
          { title: 'Accounting + Invoicing', detail: 'Revenue/expense entries, invoice records, line items, due dates, and payment state.' },
          { title: 'Appointments', detail: 'Manual + public appointment booking with Google Calendar sync support.' },
          { title: 'Admin modules', detail: 'Organizations, user control, reports, audit logs, settings, alerts, and system health.' },
        ],
      },
      {
        id: 'security',
        title: 'Security and Access Strategy',
        image: '/imgs/mockups/dev/DEV_7.png',
        list: [
          'Session security with HttpOnly auth cookies and CSRF token validation.',
          'Capability middleware maps route groups to user module access before backend actions run.',
          'Organization scoping helpers block cross-organization reads and writes for local admins.',
          'Environment exposure tests keep browser-visible VITE variables intentionally allowlisted.',
          'Secret encryption supports Google Calendar OAuth tokens and hosted runtime safeguards.',
        ],
      },
      {
        id: 'data-architecture',
        title: 'Data Architecture',
        image: '/imgs/mockups/dev/DEV_8.png',
        cards: [
          { title: 'Organization-first model', detail: 'Core entities are scoped by organization, with hierarchy support for parent and child organizations.' },
          { title: 'Relational role mapping', detail: 'Roles and users map permissions and operational ownership.' },
          { title: 'ERP domain entities', detail: 'Bookings, accounting entries, invoices, invoice line items, rent tenants, rent payments, productivity entries, and todos share consistent indexing.' },
          { title: 'Prisma migrations', detail: 'Schema evolution maintained with migration history in version control.' },
        ],
      },
      {
        id: 'integrations',
        title: 'Integrations and Automations',
        image: '/imgs/mockups/dev/DEV_9.png',
        list: [
          'Google Calendar OAuth flow for booking sync, callback processing, and disconnect actions.',
          'Productivity coach endpoint connected to OpenAI Responses API for planning guidance.',
          'Scheduled report and reminder jobs support rent summaries, accounting reminders, invoice email delivery, and alerts.',
          'Live job-board aggregation from Remotive and Arbeitnow for opportunity tracking.',
          'Trust and site-status checks across related platforms for operational visibility.',
        ],
      },
      {
        id: 'results',
        title: 'Implementation Outcomes',
        image: '/imgs/mockups/dev/DEV_10.png',
        compare: {
          beforeLabel: 'Before',
          before: [
            'Ops, rent, finance, appointments, and reporting tracked across disconnected surfaces',
            'Backend routing concentrated in broad handlers',
            'Limited module-level access boundaries for non-admin roles',
            'Manual checks for reports, reminders, and system status',
          ],
          afterLabel: 'After',
          after: [
            'One Dev ERP workspace for operations, finance, rent, appointments, and monitoring',
            'Modular Express route slices composed by the runtime app',
            'Cookie + CSRF + capability-gated API access model',
            'Centralized reports, alerts, audit logs, and system-health visibility',
          ],
        },
      },
    ],
    actions: [
      { label: 'View live Dev ERP', href: 'https://dev.nanaabaackah.com', external: true },
      { label: 'Back to projects', href: '/projects' },
    ],
  },
  {
    slug: 'odoo',
    seo: {
      title: 'Projects | Odoo ERP Customization | By Nana',
      description:
        'Case study: Odoo customization and workflow automation across CRM, projects, finance, and operations.',
      path: '/projects/odoo',
    },
    eyebrow: 'Case study',
    title: 'Odoo ERP Customization',
    summary:
      'Cross-department Odoo delivery focused on safe automation, strong adoption, and clearer reporting across the delivery lifecycle.',
    heroImage: '/imgs/mockups/ineng/INENG_1.png',
    supportingImages: ['/imgs/mockups/ineng/INENG_2.png', '/imgs/mockups/ineng/INENG_3.png'],
    discoveryImage: '/imgs/mockups/ineng/INENG_4.png',
    pills: ['ERP automation', 'Python + ORM', 'QWeb/XML', 'Odoo Studio', 'Odoo.sh'],
    heroFacts: [
      { label: 'Deliverables', value: 'ERP Workflow Customization' },
      { label: 'Stack', value: 'Python/ORM, QWeb/XML, Studio, Odoo.sh, GitHub' },
      { label: 'Role', value: 'ERP Systems Manager & Developer' },
      { label: 'Service', value: 'Automation + Odoo Development' },
    ],
    atAGlance: [
      { label: 'Role', value: 'ERP systems manager (product + delivery lead)' },
      { label: 'Users', value: 'Ops, Finance, Project leads, Sales, HR' },
      { label: 'Scope', value: 'CRM to delivery to accounting workflows' },
      { label: 'Tools', value: 'Python/ORM, QWeb/XML, Studio, Odoo.sh, GitHub' },
    ],
    stats: [
      { value: '50%+', label: 'Workflow automation gains' },
      { value: '90%', label: 'Adoption in first 3 months' },
      { value: '5 depts', label: 'Cross-functional rollout coverage' },
      { value: '1 playbook', label: 'Training + office-hours enablement' },
    ],
    challenges: [
      'Before automation, teams repeatedly re-entered the same records across CRM, project, and accounting workflows, creating unnecessary handoffs and introducing avoidable data errors.',
      'Status updates and notifications were handled manually across departments, so follow-ups depended heavily on individual habits rather than consistent process rules.',
      'Reporting required frequent cleanup because naming conventions, record ownership, and state transitions were not standardized between operations, sales, and finance.',
    ],
    storefrontShowcase: {
      label: '[Operations Workspace]',
      headline:
        'A CLEAN OPERATIONAL FRONTEND NOW SITS ON TOP OF CORE ERP AUTOMATIONS.',
      paragraphs: [
        'The interface gives operations, sales, and finance teams a unified workspace where day-to-day actions are clear, consistent, and easier to execute.',
        'Each screen is connected to backend ERP workflows for records, states, and notifications, so frontend updates and business logic stay synchronized across the full system.',
      ],
      image: '/imgs/mockups/ineng/INENG_5.png',
    },
    sections: [
      {
        id: 'constraints',
        title: 'Delivery Constraints',
        image: '/imgs/mockups/ineng/INENG_6.png',
        list: [
          'High-stakes workflows required safe, reversible, audit-friendly changes.',
          'Mixed user comfort levels across power and occasional users.',
          'Data consistency issues around naming and state ownership.',
          'Adoption risk required docs and training to ship with features.',
        ],
      },
      {
        id: 'approach',
        title: 'Approach',
        image: '/imgs/mockups/ineng/INENG_7.png',
        cards: [
          { title: 'Discovery', detail: 'Interviews, workflow mapping, and data audits.' },
          { title: 'Build', detail: 'Python logic, QWeb/XML views, and Studio configuration in sprints.' },
          { title: 'Enable', detail: 'Staged QA on Odoo.sh, training, docs, and adoption tracking.' },
        ],
      },
      {
        id: 'workflow-shift',
        title: 'Workflow Shift',
        image: '/imgs/mockups/ineng/INENG_8.png',
        compare: {
          beforeLabel: 'Before',
          before: [
            'Manual handoffs across sales, projects, and finance',
            'Inconsistent project naming and identifiers',
            'Duplicate or missed notifications',
            'Invoice states checked manually',
          ],
          afterLabel: 'After',
          after: [
            'Automated CRM → Project → Accounting transitions',
            'Standardized project IDs and naming',
            'Deduplicated notifications with fallbacks',
            'Automated invoice status alerts',
          ],
        },
      },
      {
        id: 'highlights',
        title: 'Automation Highlights',
        image: '/imgs/mockups/ineng/INENG_9.png',
        cards: [
          {
            title: 'Email deduplication',
            detail: 'Grouped recipients and added team-level fallbacks to reduce noise and misses.',
          },
          {
            title: 'Invoice status alerts',
            detail: 'Template-driven payment-state notifications for finance without manual checks.',
          },
          {
            title: 'Project numbering',
            detail: 'Auto-generated IDs/names for cleaner reporting and traceability.',
          },
        ],
      },
    ],
    actions: [
      { label: 'Back to projects', href: '/projects' },
      { label: 'Book a working session', href: 'https://dev.nanaabaackah.com/book', external: true },
    ],
  },
  {
    slug: 'kids-party-shop-rental',
    seo: {
      title: 'Projects | Kids Party Shop + Rental Portal ERP | By Nana',
      description:
        'Case study: split kids party shop and rental business public website, admin portal, and Netlify Functions backend for bookings, inventory, accounting, delivery, HR, and operations.',
      path: '/projects/kids-party-shop-rental',
    },
    eyebrow: 'Flagship case study',
    title: 'Kids Party Shop + Rental Portal ERP',
    summary:
      'A live React/Vite public website for a kids party shop and rental business, paired with a dedicated admin portal and portal-owned Netlify Functions backend across POS orders, bookings, inventory, delivery, documents, accounting, maintenance, marketing, HR, and workforce management.',
    heroImage: '/imgs/mockups/reebs/REEBS_2.png',
    supportingImages: ['/imgs/mockups/reebs/REEBS_3.png', '/imgs/mockups/reebs/REEBS_7.png'],
    discoveryImage: '/imgs/mockups/reebs/REEBS_5.png',
    pills: ['Live website', 'Portal ERP', 'Netlify Functions', 'Inventory + Finance', 'Ops + HR'],
    heroFacts: [
      { label: 'Deliverables', value: 'Public Website + Admin Portal ERP' },
      { label: 'Stack', value: 'React/Vite, Netlify Functions, PostgreSQL, Prisma, Shared Workspace Packages' },
      { label: 'Role', value: 'Full-Stack Product Engineer' },
      { label: 'Service', value: 'Architecture + Product Delivery' },
    ],
    atAGlance: [
      { label: 'Platform', value: 'Kids party shop and rental business website + portal backend/admin ERP' },
      { label: 'Users', value: 'Customers, admin, managers, delivery crew, finance, HR, operations staff' },
      {
        label: 'Scope',
        value:
          'Website pages, shop, rentals, cart, checkout, POS/order builder, bookings, orders, stock movement, invoicing, expenses, delivery, documents, maintenance, timesheets, roles, marketing, operations workflows',
      },
      { label: 'Stack', value: 'React + Vite, Netlify Functions, PostgreSQL (Railway), Prisma schema and migrations, shared shell/runtime packages' },
    ],
    stats: [
      { value: '2 deploy targets', label: 'Public website and portal/backend split' },
      { value: '40+ functions', label: 'Portal-owned backend endpoints' },
      { value: '3 sales paths', label: 'Website checkout, staff POS orders, and rental bookings' },
      { value: 'Integer cents', label: 'Financial accuracy across reports and invoices' },
    ],
    challenges: [
      'The customer-facing website and internal ERP needed clearer ownership so public pages could stay lightweight while admin workflows, functions, and Prisma migrations lived in the portal app.',
        'Retail sales, staff-created POS orders, and rental reservations shared inventory but followed different workflows, creating overbooking risk and inconsistent stock state transitions.',
      'Delivery, documents, accounting, marketing, maintenance, HR, timesheets, and newer operations workflows needed to stay visible in the portal without leaking admin concerns back into the public website.',
    ],
    storefrontShowcase: {
      label: '[Website + Portal ERP]',
      headline:
        'THE PUBLIC WEBSITE NOW HANDS OPERATIONAL WORK TO A DEDICATED PORTAL BACKEND.',
      paragraphs: [
        'Customers move through shopping, rentals, booking, checkout, and support pages in the public website while staff and managers work from the portal admin workspace and POS/order builder.',
        'Portal-owned Netlify Functions write to shared order, booking, inventory, delivery, document, accounting, HR, and operations services, while shared organization utilities keep requests aligned across the split apps.',
      ],
      image: '/imgs/mockups/reebs/REEBS_1.png',
    },
    diagrams: [
      {
        id: 'system-layout',
        type: 'architecture',
        title: 'Architecture Diagram',
        caption: 'Public website, admin portal, portal-owned functions, data layer, shared packages, and external integrations.',
        ariaLabel:
          'System architecture showing a kids party shop and rental business public website, admin portal, POS order builder, shared workspace packages, portal Netlify functions, PostgreSQL, WhatsApp and push notifications, and geocoding services.',
        nodes: [
          { id: 'website', label: 'Public Website', detail: 'Shop, rentals, book, cart', x: 13, y: 18, tone: 'accent' },
          { id: 'checkout', label: 'Checkout Flow', detail: 'Customer orders', x: 43, y: 5, tone: 'light' },
          { id: 'booking-flow', label: 'Booking Flow', detail: 'Rental intake', x: 57, y: 5, tone: 'light' },
          { id: 'portal', label: 'Admin Portal', detail: 'ERP and staff routes', x: 87, y: 18, tone: 'accent' },
          { id: 'shared', label: 'Shared Packages', detail: 'Shell, org, template config', x: 50, y: 31, tone: 'light' },
          { id: 'pos', label: 'POS Order Builder', detail: 'Search, SKU, barcode input', x: 86, y: 42, tone: 'light' },
          { id: 'scan', label: 'Future Camera Scan', detail: 'Planned item lookup flow', x: 18, y: 43, tone: 'base' },
          { id: 'api', label: 'Portal Functions API', detail: 'Auth, rules, writes', x: 50, y: 56, tone: 'accent' },
          { id: 'prisma', label: 'Prisma ORM', detail: 'Schema and migrations', x: 42, y: 75, tone: 'light' },
          { id: 'db', label: 'PostgreSQL Database', detail: 'Operational source of truth', x: 58, y: 84, tone: 'light' },
          { id: 'whatsapp', label: 'WhatsApp Alerts', detail: 'Manager messages', x: 14, y: 87, tone: 'base' },
          { id: 'push', label: 'Push Notifications', detail: 'Manager alerts', x: 28, y: 87, tone: 'base' },
          { id: 'geocode', label: 'Geocoding Services', detail: 'Nominatim with Google fallback', x: 82, y: 87, tone: 'base' },
        ],
        edges: [
          { from: 'website', to: 'api', label: 'public APIs', labelT: 0.48, labelOffset: -1.4 },
          { from: 'checkout', to: 'api', label: 'orders', labelT: 0.54, labelOffset: -1.8 },
          { from: 'booking-flow', to: 'api', label: 'bookings' },
          { from: 'portal', to: 'api', label: 'staff APIs', labelT: 0.52, labelOffset: 1.6 },
          { from: 'portal', to: 'pos', label: 'walk-in sales' },
          { from: 'pos', to: 'api', label: 'create order' },
          { from: 'scan', to: 'pos', label: 'planned scan input' },
          { from: 'website', to: 'shared', label: 'runtime helpers', labelT: 0.5, labelOffset: 1.4 },
          { from: 'portal', to: 'shared', label: 'shell and org scope', labelT: 0.5, labelOffset: -1.4 },
          { from: 'shared', to: 'api', label: 'headers and config' },
          { from: 'api', to: 'prisma', label: 'data access' },
          { from: 'prisma', to: 'db', label: 'SQL queries' },
          { from: 'api', to: 'whatsapp', label: 'WhatsApp notices' },
          { from: 'api', to: 'push', label: 'push notices' },
          { from: 'api', to: 'geocode', label: 'address lookup' },
        ],
      },
      {
        id: 'database-layout',
        type: 'class',
        title: 'Database Class Diagram',
        caption: 'Core portal-owned classes and relationships behind customer flows, operations, inventory, and finance.',
        ariaLabel:
          'Database class diagram showing organization, users, customers, products, orders and bookings, stock movements, documents, financials, maintenance, vendors, timesheets, roles, and marketing records.',
        nodes: [
          {
            id: 'org',
            label: 'Organization',
            tone: 'accent',
            attributes: ['id: uuid', 'name: string', 'slug: string', 'settings: json', 'status: enum'],
          },
          {
            id: 'user',
            label: 'User',
            tone: 'light',
            attributes: ['id: uuid', 'organizationId: fk', 'roleId: fk', 'email: string', 'status: enum'],
          },
          {
            id: 'employeeProfile',
            label: 'EmployeeProfile',
            tone: 'light',
            attributes: ['id: uuid', 'userId: fk', 'name: string', 'phone: string', 'position: string'],
          },
          {
            id: 'role',
            label: 'Role',
            tone: 'light',
            attributes: ['id: uuid', 'organizationId: fk', 'name: string', 'permissions: json'],
          },
          {
            id: 'customers',
            label: 'Customer',
            tone: 'light',
            attributes: ['id: uuid', 'organizationId: fk', 'name: string', 'phone: string', 'address: json'],
          },
          {
            id: 'products',
            label: 'Product',
            tone: 'accent',
            attributes: ['id: uuid', 'organizationId: fk', 'sku: string', 'barcode: string', 'stockType: enum'],
          },
          {
            id: 'order',
            label: 'Order',
            tone: 'accent',
            attributes: ['id: uuid', 'customerId: fk', 'channel: enum', 'status: enum', 'total: decimal'],
          },
          {
            id: 'booking',
            label: 'Booking',
            tone: 'accent',
            attributes: ['id: uuid', 'customerId: fk', 'eventDate: datetime', 'status: enum', 'total: decimal'],
          },
          {
            id: 'orderItem',
            label: 'OrderItem',
            tone: 'light',
            attributes: ['id: uuid', 'orderId: fk', 'productId: fk', 'quantity: int', 'unitPrice: decimal'],
          },
          {
            id: 'bookingItem',
            label: 'BookingItem',
            tone: 'light',
            attributes: ['id: uuid', 'bookingId: fk', 'productId: fk', 'quantity: int', 'rentalPrice: decimal'],
          },
          {
            id: 'stock',
            label: 'StockMovement',
            tone: 'light',
            attributes: ['id: uuid', 'productId: fk', 'sourceType: enum', 'quantityDelta: int', 'createdAt: datetime'],
          },
          {
            id: 'delivery',
            label: 'Delivery',
            tone: 'light',
            attributes: ['id: uuid', 'orderId: fk', 'bookingId: fk', 'status: enum', 'scheduledAt: datetime'],
          },
          {
            id: 'document',
            label: 'Document',
            tone: 'light',
            attributes: ['id: uuid', 'orderId: fk', 'bookingId: fk', 'type: enum', 'fileUrl: string'],
          },
          {
            id: 'expense',
            label: 'Expense',
            tone: 'base',
            attributes: ['id: uuid', 'organizationId: fk', 'category: string', 'amount: decimal', 'postedAt: datetime'],
          },
          {
            id: 'financialRecord',
            label: 'FinancialRecord',
            tone: 'base',
            attributes: ['id: uuid', 'organizationId: fk', 'sourceType: enum', 'amount: decimal', 'postedAt: datetime'],
          },
          {
            id: 'maintenance',
            label: 'Maintenance',
            tone: 'base',
            attributes: ['id: uuid', 'productId: fk', 'vendorId: fk', 'status: enum', 'scheduledAt: datetime'],
          },
          {
            id: 'vendor',
            label: 'Vendor',
            tone: 'base',
            attributes: ['id: uuid', 'organizationId: fk', 'name: string', 'phone: string', 'serviceType: string'],
          },
          {
            id: 'timesheet',
            label: 'Timesheet',
            tone: 'base',
            attributes: ['id: uuid', 'userId: fk', 'clockIn: datetime', 'clockOut: datetime', 'status: enum'],
          },
        ],
        edges: [
          { from: 'org', to: 'user', label: '1 -> many' },
          { from: 'org', to: 'role', label: '1 -> many' },
          { from: 'org', to: 'customers', label: '1 -> many' },
          { from: 'org', to: 'products', label: '1 -> many' },
          { from: 'org', to: 'expense', label: '1 -> many' },
          { from: 'org', to: 'vendor', label: '1 -> many' },
          { from: 'role', to: 'user', label: '1 -> many' },
          { from: 'user', to: 'employeeProfile', label: '1 -> 1' },
          { from: 'user', to: 'timesheet', label: '1 -> many' },
          { from: 'customers', to: 'order', label: '1 -> many' },
          { from: 'customers', to: 'booking', label: '1 -> many' },
          { from: 'order', to: 'orderItem', label: '1 -> many' },
          { from: 'booking', to: 'bookingItem', label: '1 -> many' },
          { from: 'products', to: 'orderItem', label: '1 -> many' },
          { from: 'products', to: 'bookingItem', label: '1 -> many' },
          { from: 'orderItem', to: 'stock', label: 'creates' },
          { from: 'bookingItem', to: 'stock', label: 'creates' },
          { from: 'order', to: 'delivery', label: '1 -> many' },
          { from: 'booking', to: 'delivery', label: '1 -> many' },
          { from: 'order', to: 'document', label: '1 -> many' },
          { from: 'booking', to: 'document', label: '1 -> many' },
          { from: 'order', to: 'financialRecord', label: 'rolls into' },
          { from: 'booking', to: 'financialRecord', label: 'rolls into' },
          { from: 'products', to: 'maintenance', label: '1 -> many' },
          { from: 'vendor', to: 'maintenance', label: '1 -> many' },
        ],
      },
    ],
    sections: [
      {
        id: 'commerce-layer',
        title: 'Commerce Layer (Public Website)',
        image: '/imgs/mockups/reebs/REEBS_14.png',
        summary:
          'The public layer stays focused on the kids party shop and rental customer journey: informational pages, product discovery, rentals, cart, checkout, and booking forms.',
        cards: [
          { title: 'Shop + rentals', detail: 'Public browsing for retail items and rental inventory without exposing admin routes.' },
          { title: 'Checkout path', detail: 'Customer capture and order creation through the portal-owned createOrder function.' },
          { title: 'Booking intake', detail: 'Event details and rental items posted from the website into the bookings function.' },
          { title: 'Support content', detail: 'FAQ, contact, delivery, refund, privacy, and terms pages reduce pre-booking friction.' },
        ],
      },
      {
        id: 'pos-module',
        title: 'POS and In-Store Sales Module',
        image: '/imgs/mockups/reebs/REEBS_15.png',
        summary:
          'The portal includes a POS/order builder path for staff-created sales, with a future camera scanning workflow scoped for faster item lookup.',
        cards: [
          { title: 'Order builder', detail: 'Staff can build walk-in sales from portal inventory and submit order records through the backend.' },
          { title: 'SKU and barcode lookup', detail: 'Product search supports name, SKU, and barcode-style lookup so counter sales stay tied to catalog data.' },
          { title: 'Stock-aware cart lines', detail: 'Selected products feed order totals while staying aligned with available inventory and downstream stock movement logic.' },
          { title: 'Future camera scanning', detail: 'Next POS iteration can add camera-based barcode scanning for faster item capture on mobile or tablet devices.' },
        ],
      },
      {
        id: 'booking-orders',
        title: 'Booking and Order Operations Module',
        image: '/imgs/mockups/reebs/REEBS_9.png',
        summary:
          'Retail orders, POS-created orders, and rental bookings are handled as dedicated flows but consolidated inside the portal-owned operational system.',
        compare: {
          beforeLabel: 'Before',
          before: [
            'Bookings, counter sales, and online orders managed across separate surfaces',
            'Manual availability checks',
            'No fast scan path for in-store item capture',
            'No shared lifecycle status model',
          ],
          afterLabel: 'With Portal ERP',
          after: [
            'Unified POS order + booking records under one platform',
            'Product search and barcode/SKU lookup for staff sales',
            'Future camera scanning planned for faster item capture',
            'Availability-aware validations at API level',
          ],
        },
      },
      {
        id: 'inventory-control',
        title: 'Inventory and Stock Movement Module',
        image: '/imgs/mockups/reebs/REEBS_11.png',
        summary:
          'Inventory is managed as a portal-owned core service with stock movement logs, counts, and availability support for website, POS, and rental workflows.',
        cards: [
          { title: 'Stock endpoint', detail: 'Controlled stock in/out operations with user attribution.' },
          { title: 'Activity logs', detail: 'Historical movement trail for audits and variance checks.' },
          { title: 'Inventory counts', detail: 'Count snapshots and stock valuation support.' },
          { title: 'Unified catalog', detail: 'Products supporting website sales, POS order building, and rental workflows.' },
        ],
      },
      {
        id: 'financials-accounting',
        title: 'Accounting and Financials Module',
        image: '/imgs/mockups/reebs/REEBS_8.png',
        summary:
          'Financial reporting, expense capture, invoicing, and P&L visibility are connected directly to live order and booking data in the portal backend.',
        cards: [
          { title: 'Integer-based money model', detail: 'Values stored in integer cents to avoid floating-point drift.' },
          { title: 'Financials endpoint', detail: 'Revenue split, expense totals, and profitability windows.' },
          { title: 'Expenses module', detail: 'Category-driven operational expenses tied to users and dates.' },
          { title: 'Accounting view', detail: 'Receipts, invoices, trends, and finance-oriented KPIs.' },
        ],
      },
      {
        id: 'delivery-logistics',
        title: 'Delivery and Logistics Module',
        image: '/imgs/mockups/reebs/REEBS_6.png',
        summary:
          'Delivery planning and operational fulfillment are tracked from booking context through dispatch updates.',
        list: [
          'Delivery board tracks route ownership and status progression.',
          'Geocoding support maps venue addresses for planning.',
          'Operational handoffs are visible to admin and manager roles.',
          'Delivery context links back to order/booking records for clarity.',
        ],
      },
      {
        id: 'documents-invoicing',
        title: 'Documents and Invoicing Module',
        image: '/imgs/mockups/reebs/REEBS_11.png',
        cards: [
          { title: 'Document service', detail: 'Centralized storage for operational and finance files.' },
          { title: 'Invoice generation', detail: 'Branded invoice creation from transaction context.' },
          { title: 'Invoice retrieval', detail: 'Detail endpoint supports review and downstream sharing.' },
          { title: 'Close-ready records', detail: 'Receipts and invoices connected to accounting workflows.' },
        ],
      },
      {
        id: 'maintenance-asset-health',
        title: 'Maintenance and Asset Health Module',
        image: '/imgs/mockups/reebs/REEBS_12.png',
        list: [
          'Maintenance logs track service events against equipment and assets.',
          'Vendor records support supplier contacts and lead-time context.',
          'Asset lifecycle activity links maintenance events to operations reliability.',
          'Operational visibility improves readiness before booking allocation.',
        ],
      },
      {
        id: 'workforce-and-access',
        title: 'HR, Timesheets, Roles, and Access',
        image: '/imgs/mockups/reebs/REEBS_4.png',
        cards: [
          { title: 'Staff authentication', detail: 'Role-aware login and token-based API access.' },
          { title: 'HR profiles', detail: 'Employee records with contact and job details.' },
          { title: 'Timesheets', detail: 'Clock-in/out workflow support for operational crews.' },
          { title: 'Roles and permissions', detail: 'Admin/manager/staff access control by route and module.' },
        ],
      },
      {
        id: 'platform-infrastructure',
        title: 'Platform Infrastructure and Integrations',
        image: '/imgs/mockups/reebs/REEBS_13.png',
        summary:
          'The backend is built as portal-owned Netlify serverless functions with organization-level scoping, shared workspace utilities, and optional third-party integrations.',
        list: [
          'Functions layer covers auth, inventory, bookings, orders, delivery, documents, HR, marketing, maintenance, and financial services.',
          'Organization scoping supports multi-tenant-ready behavior and data isolation.',
          'WhatsApp and push-notification hooks keep managers informed on transactional events.',
          'Prisma schema and migrations maintain consistent data contracts across releases.',
          'Public website and admin portal routes stay separated while sharing one operational source of truth through the backend.',
        ],
      },
    ],
    actions: [
      { label: 'Read launch recap', href: '/blog/kids-party-shop-rental' },
      { label: 'Book a working session', href: 'https://dev.nanaabaackah.com/book', external: true },
    ],
  },
  {
    slug: 'portfolio',
    seo: {
      title: 'Projects | Portfolio Website (React) | By Nana',
      description:
        'Case study: React portfolio website built as a storytelling and conversion platform with reusable case-study and blog structure.',
      path: '/projects/portfolio',
    },
    eyebrow: 'Case study',
    title: 'Portfolio Website (React)',
    summary:
      'A custom portfolio platform built to present projects, blog content, and service positioning in a clear narrative structure that balances brand expression with technical credibility.',
    heroImage: '/imgs/mockups/portfolio/PORTFOLIO_8.png',
    supportingImages: ['/imgs/mockups/portfolio/PORTFOLIO_5.png', '/imgs/mockups/portfolio/PORTFOLIO_4.png'],
    discoveryImage: '/imgs/mockups/portfolio/PORTFOLIO_1.png',
    pills: ['Personal brand site', 'React + Vite', 'Case-study framework', 'Accessibility-aware', 'SEO-ready'],
    heroFacts: [
      { label: 'Deliverables', value: 'Portfolio Website + Case Study Pages' },
      { label: 'Stack', value: 'React, Vite, React Router, Custom CSS' },
      { label: 'Role', value: 'Product Designer + Front-End Engineer' },
      { label: 'Service', value: 'Brand Experience + Front-End Delivery' },
    ],
    atAGlance: [
      { label: 'Product', value: 'Professional portfolio and thought-leadership website' },
      { label: 'Users', value: 'Potential clients, hiring teams, and collaborators' },
      { label: 'Goal', value: 'Showcase capability through detailed case studies and clear conversion paths' },
      { label: 'Tools', value: 'React, Vite, React Router, Custom CSS, Netlify deployment workflow' },
    ],
    stats: [
      { value: '5+', label: 'Featured project case studies' },
      { value: '2 content types', label: 'Project + blog architecture' },
      { value: 'Mobile-first', label: 'Responsive layout strategy' },
      { value: 'Reusable', label: 'Structured detail-page framework' },
    ],
    challenges: [
      'The portfolio needed to communicate both design thinking and engineering depth without overwhelming first-time visitors with dense technical content.',
      'Project narratives had to be modular and reusable so new case studies could be added quickly while maintaining consistent quality and structure.',
      'The website needed to feel distinctive in presentation but still stay readable, performant, and accessible across desktop and mobile devices.',
    ],
    storefrontShowcase: {
      label: '[Portfolio Experience]',
      headline:
        'THE WEBSITE COMBINES BRAND STORYTELLING WITH STRUCTURED TECHNICAL BREAKDOWNS.',
      paragraphs: [
        'Each section is intentionally sequenced to guide visitors from context to implementation details, helping them understand both outcomes and process.',
        'Under the visual layer, reusable page patterns and content blocks make it easy to scale project and blog content without redesigning the site structure for every update.',
      ],
      image: '/imgs/mockups/portfolio/PORTFOLIO_10.png',
    },
    sections: [
      {
        id: 'strategy',
        title: 'Content and Narrative Strategy',
        image: '/imgs/mockups/portfolio/PORTFOLIO_6.png',
        list: [
          'Mapped audience intent into clear paths for services, projects, and contact.',
          'Built case-study storytelling around context, constraints, decisions, and outcomes.',
          'Created consistent section architecture so every project page remains easy to scan.',
          'Balanced visual personality with direct, evidence-based technical writing.',
        ],
      },
      {
        id: 'information-architecture',
        title: 'Information Architecture',
        image: '/imgs/mockups/portfolio/PORTFOLIO_7.png',
        cards: [
          { title: 'Route system', detail: 'Dedicated routes for Home, About, Projects, Contact, Blog, and dynamic detail pages.' },
          { title: 'Project data model', detail: 'Case studies are driven by structured content objects for maintainable updates.' },
          { title: 'Blog structure', detail: 'Post lists and detail pages reuse shared metadata and body sections.' },
          { title: 'Navigation clarity', detail: 'Global navigation and page hierarchy reduce click uncertainty.' },
        ],
      },
      {
        id: 'frontend-execution',
        title: 'Frontend Execution',
        image: '/imgs/mockups/portfolio/PORTFOLIO_9.png',
        cards: [
          { title: 'Component reuse', detail: 'Shared UI blocks for CTAs, image handling, metadata, and page sections.' },
          { title: 'Animation layer', detail: 'Scroll-reveal and motion accents support hierarchy without distracting from content.' },
          { title: 'Theme support', detail: 'Light and dark modes are coordinated through global design tokens.' },
          { title: 'Media handling', detail: 'Mockups and visuals are mapped per project for clear contextual storytelling.' },
        ],
      },
      {
        id: 'quality',
        title: 'Performance, Accessibility, and SEO',
        image: '/imgs/mockups/portfolio/PORTFOLIO_2.png',
        list: [
          'Route-level SEO metadata for project and blog detail pages.',
          'Semantic headings, readable type scaling, and keyboard-friendly interaction patterns.',
          'Optimized image usage with lazy loading across visual-heavy sections.',
          'Vite build pipeline keeps delivery fast for production deployment.',
        ],
      },
      {
        id: 'outcomes',
        title: 'Outcome and Ongoing Iteration',
        image: '/imgs/mockups/portfolio/PORTFOLIO_3.png',
        compare: {
          beforeLabel: 'Before',
          before: [
            'Portfolio content existed in fragmented or static formats',
            'Limited space for process-level project storytelling',
            'Harder to maintain consistency across new case studies',
            'Fewer structured pathways to contact and conversion',
          ],
          afterLabel: 'After',
          after: [
            'Unified website with scalable project and blog architecture',
            'Detailed case-study format that shows decision-making and implementation',
            'Reusable content model for faster ongoing updates',
            'Clear conversion routes through CTAs and contact flows',
          ],
        },
      },
    ],
    actions: [
      { label: 'View GitHub repository', href: 'https://github.com/nanaabaackah/bynana-portfolio', external: true },
      { label: 'Visit live website', href: 'https://nanaabaackah.com', external: true },
      { label: 'Back to projects', href: '/projects' },
    ],
  },
];

export const projectDetailsBySlug = Object.fromEntries(
  projectDetails.map((project) => [project.slug, project]),
);
