import {
  ERP_MODULE_GROUPS,
  ERP_MODULE_STATES,
  ERP_MODULE_STATUSES,
  ERP_MODULE_VISIBILITY,
} from "@faako/config";

const DEFAULT_MODULE_STATE = {
  visibility: ERP_MODULE_VISIBILITY.VISIBLE,
  state: ERP_MODULE_STATES.ENABLED,
};

export const FAAKO_ERP_ADMIN_MODULES = [
  {
    key: "dashboard",
    label: "Dashboard",
    ...DEFAULT_MODULE_STATE,
    path: "/",
    group: ERP_MODULE_GROUPS.CORE,
    status: ERP_MODULE_STATUSES.STABLE,
    core: true,
    navOrder: 10,
    bottomNav: true,
    bottomOrder: 10,
    defaultBottomLabel: "Home",
  },
  {
    key: "orders",
    label: "Orders",
    ...DEFAULT_MODULE_STATE,
    path: "/orders",
    group: ERP_MODULE_GROUPS.SALES,
    status: ERP_MODULE_STATUSES.STABLE,
    core: true,
    navOrder: 20,
    bottomNav: true,
    bottomOrder: 20,
  },
  {
    key: "inventory",
    label: "Inventory",
    ...DEFAULT_MODULE_STATE,
    path: "/inventory",
    group: ERP_MODULE_GROUPS.OPERATIONS,
    status: ERP_MODULE_STATUSES.STABLE,
    core: true,
    navOrder: 30,
    bottomNav: true,
    bottomOrder: 30,
    defaultBottomLabel: "Stock",
  },
  {
    key: "bookings",
    label: "Bookings",
    ...DEFAULT_MODULE_STATE,
    path: "/bookings",
    group: ERP_MODULE_GROUPS.OPERATIONS,
    status: ERP_MODULE_STATUSES.STABLE,
    navOrder: 40,
  },
  {
    key: "vendors",
    label: "Vendors",
    ...DEFAULT_MODULE_STATE,
    path: "/vendors",
    group: ERP_MODULE_GROUPS.OPERATIONS,
    status: ERP_MODULE_STATUSES.STABLE,
    navOrder: 50,
  },
  {
    key: "expenses",
    label: "Expenses",
    ...DEFAULT_MODULE_STATE,
    path: "/expenses",
    group: ERP_MODULE_GROUPS.FINANCE,
    status: ERP_MODULE_STATUSES.STABLE,
    navOrder: 60,
  },
  {
    key: "finance",
    label: "Finance",
    ...DEFAULT_MODULE_STATE,
    path: "/finance",
    group: ERP_MODULE_GROUPS.FINANCE,
    status: ERP_MODULE_STATUSES.STABLE,
    navOrder: 70,
  },
  {
    key: "reports",
    label: "Reports",
    ...DEFAULT_MODULE_STATE,
    path: "/reports",
    group: ERP_MODULE_GROUPS.INSIGHTS,
    status: ERP_MODULE_STATUSES.STABLE,
    navOrder: 80,
  },
  {
    key: "people",
    label: "People",
    ...DEFAULT_MODULE_STATE,
    path: "/people",
    group: ERP_MODULE_GROUPS.TEAM,
    status: ERP_MODULE_STATUSES.STABLE,
    navOrder: 90,
  },
  {
    key: "customers",
    label: "Customers",
    ...DEFAULT_MODULE_STATE,
    path: "/customers",
    group: ERP_MODULE_GROUPS.TEAM,
    status: ERP_MODULE_STATUSES.STABLE,
    navOrder: 100,
    bottomNav: true,
    bottomOrder: 40,
    defaultBottomLabel: "CRM",
  },
  {
    key: "notifications",
    label: "Alerts",
    ...DEFAULT_MODULE_STATE,
    path: "/notifications",
    group: ERP_MODULE_GROUPS.INSIGHTS,
    status: ERP_MODULE_STATUSES.STABLE,
    navOrder: 110,
  },
  {
    key: "modules",
    label: "Modules",
    ...DEFAULT_MODULE_STATE,
    path: "/modules",
    group: ERP_MODULE_GROUPS.SYSTEM,
    status: ERP_MODULE_STATUSES.IN_PROGRESS,
    navOrder: 120,
  },
  {
    key: "settings",
    label: "Settings",
    ...DEFAULT_MODULE_STATE,
    path: "/settings",
    group: ERP_MODULE_GROUPS.SYSTEM,
    status: ERP_MODULE_STATUSES.STABLE,
    core: true,
    navOrder: 130,
    bottomNav: true,
    bottomOrder: 50,
  },
];

export default FAAKO_ERP_ADMIN_MODULES;
